import { useEffect, useMemo, useState } from "react";
import { Plus, Search, Trash2, X, FileText, Wallet } from "lucide-react";
import * as api from "../api";

export default function CustomersPage({docs=[],payments=[]}){
 const [items,setItems]=useState([]),[q,setQ]=useState(""),[selected,setSelected]=useState(null);
 const [form,setForm]=useState({name:"",phone:"",email:"",gstin:"",state:"",address:""});
 useEffect(()=>{api.getCustomers().then(setItems).catch(()=>{})},[]);
 const save=async()=>{if(!form.name.trim())return;const x=await api.createCustomer(form);setItems(v=>[...v,x]);setForm({name:"",phone:"",email:"",gstin:"",state:"",address:""})};
 const del=async id=>{if(!confirm("Delete this customer?"))return;await api.deleteCustomer(id);setItems(v=>v.filter(x=>x.id!==id));if(selected?.id===id)setSelected(null)};
 const filtered=useMemo(()=>items.filter(x=>(x.name+" "+x.phone+" "+x.gstin).toLowerCase().includes(q.toLowerCase())),[items,q]);
 const history=selected?[...docs.filter(d=>d.partyName===selected.name).map(d=>({...d,kind:"doc",amount:d.total})),...payments.filter(p=>p.partyName===selected.name).map(p=>({...p,kind:"payment",amount:p.amount}))].sort((a,b)=>new Date(b.date)-new Date(a.date)):[];
 const billed=history.filter(x=>x.kind==="doc"&&x.type==="invoice").reduce((s,x)=>s+Number(x.amount||0),0);
 const received=history.filter(x=>x.kind==="payment").reduce((s,x)=>s+Number(x.amount||0),0);
 return <div>
  <div className="bb-page-head"><div><h2>Customers</h2><span>Customer master, transaction history and outstanding balances.</span></div></div>
  <div className="bb-card" style={{marginBottom:14}}><div className="bb-section-title">Add Customer</div><div className="bb-row3">{["name","phone","email","gstin","state","address"].map(k=><input key={k} className="bb-input" placeholder={{name:"Customer name",phone:"Phone",email:"Email",gstin:"GSTIN",state:"State",address:"Address"}[k]} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}</div><button className="bb-btn bb-btn-primary" style={{marginTop:10}} onClick={save}><Plus size={14}/> Save Customer</button></div>
  <div className="bb-card"><div className="bb-section-title"><span>Customer List ({items.length})</span><div className="bb-search-wrap" style={{maxWidth:280}}><Search size={14}/><input className="bb-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers"/></div></div><table className="bb-table"><thead><tr><th>Name</th><th>Phone</th><th>GSTIN</th><th>State</th><th>Outstanding</th><th></th></tr></thead><tbody>{filtered.map(x=>{const inv=docs.filter(d=>d.type==="invoice"&&d.partyName===x.name).reduce((s,d)=>s+Number(d.total||0),0);const rec=payments.filter(p=>p.partyName===x.name).reduce((s,p)=>s+Number(p.amount||0),0);return <tr key={x.id}><td><button className="bb-link-btn" onClick={()=>setSelected(x)}><b>{x.name}</b></button><div style={{fontSize:11,color:"var(--muted)"}}>{x.email||"—"}</div></td><td>{x.phone||"—"}</td><td>{x.gstin||"—"}</td><td>{x.state||"—"}</td><td className="bb-mono">{fmtMoney(Math.max(inv-rec,0))}</td><td><button className="bb-icon-btn" onClick={()=>del(x.id)}><Trash2 size={15}/></button></td></tr>})}</tbody></table>{!filtered.length&&<div className="bb-empty">No customers found.</div>}</div>
  {selected&&<div className="bb-modal-backdrop"><div className="bb-modal"><div className="bb-page-head"><div><h2>{selected.name}</h2><span>{selected.phone||"No phone"} · {selected.gstin||"No GSTIN"}</span></div><button className="bb-icon-btn" onClick={()=>setSelected(null)}><X size={17}/></button></div><div className="bb-stat-grid"><div className="bb-stat-card"><div className="bb-stat-label">Billed</div><div className="bb-stat-value">{fmtMoney(billed)}</div></div><div className="bb-stat-card"><div className="bb-stat-label">Received</div><div className="bb-stat-value">{fmtMoney(received)}</div></div><div className="bb-stat-card"><div className="bb-stat-label">Outstanding</div><div className="bb-stat-value">{fmtMoney(Math.max(billed-received,0))}</div></div></div><div className="bb-section-title"><FileText size={15}/> Transaction History</div>{history.slice(0,15).map(x=><div key={x.kind+x.id} style={{display:"flex",justifyContent:"space-between",padding:"9px 0",borderBottom:"1px solid var(--border)"}}><span>{x.kind==="doc"?x.number:"Payment "+x.number}<small style={{display:"block",color:"var(--muted)"}}>{x.kind==="doc"?x.type:"Payment In"} · {x.date}</small></span><b>{fmtMoney(x.amount)}</b></div>)}{!history.length&&<div className="bb-empty">No transactions yet.</div>}</div></div>}
 </div>;
}
function fmtMoney(v){return "₹"+Number(v||0).toLocaleString("en-IN",{maximumFractionDigits:2})}