import { useEffect, useState } from "react";
import { Plus, Search, Trash2, X, FileText, Wallet } from "lucide-react";
import * as api from "../api";
export default function CustomersPage({docs=[],payments=[]}){
 const [items,setItems]=useState([]),[q,setQ]=useState(""),[selected,setSelected]=useState(null),[form,setForm]=useState({name:"",phone:"",email:"",gstin:"",state:"",address:""});
 useEffect(()=>{api.getCustomers().then(setItems)},[]);
 const save=async()=>{if(!form.name.trim())return;const x=await api.createCustomer(form);setItems(v=>[...v,x]);setForm({name:"",phone:"",email:"",gstin:"",state:"",address:""});};
 const del=async id=>{await api.deleteCustomer(id);setItems(v=>v.filter(x=>x.id!==id));};
 return <div><div className="bb-page-head"><div><h2>Customers</h2><span>Keep customer details ready for one-click invoicing.</span></div></div><div className="bb-card" style={{marginBottom:14}}><div className="bb-section-title">Add Customer</div><div className="bb-row3">{["name","phone","email","gstin","state","address"].map(k=><input key={k} className="bb-input" placeholder={{name:"Customer name",phone:"Phone",email:"Email",gstin:"GSTIN",state:"State",address:"Address"}[k]} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}</div><button className="bb-btn bb-btn-primary" style={{marginTop:10}} onClick={save}><Plus size={14}/> Save Customer</button></div><div className="bb-card"><div className="bb-section-title"><span>Customer List ({items.length})</span><div className="bb-search-wrap" style={{maxWidth:260}}><Search size={14}/><input className="bb-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers"/></div></div><table className="bb-table"><thead><tr><th>Name</th><th>Phone</th><th>GSTIN</th><th>State</th><th></th></tr></thead><tbody>{items.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())).map(x=><tr key={x.id}><td><button style={{border:0,background:"none",padding:0,cursor:"pointer",color:"inherit",fontWeight:700}} onClick={()=>setSelected(x)}><b>{x.name}</b></button><div style={{fontSize:11,color:"var(--muted)"}}>{x.email}</div></td><td>{x.phone||"—"}</td><td>{x.gstin||"—"}</td><td>{x.state||"—"}</td><td><button className="bb-icon-btn" onClick={()=>del(x.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!items.length&&<div className="bb-empty">No customers yet.</div>}</div></div>;
}