import { useMemo, useState } from "react";
import { ArrowLeft, Check, Palette, Save, Sparkles, Trash2, Type, Image as ImageIcon, Minus, Square, Hash, QrCode, Plus, Move } from "lucide-react";
import { DOCUMENT_DESIGNS } from "../utils/documentDesigns";

const blank = { preset:"classic", accent:"#16233f", header:"classic", density:"normal", radius:4, font:"Inter", table:"grid", paperBg:"#ffffff", lineColor:"#d8dde5", logoPosition:"left", showLogo:true, showTaxSummary:true, showAmountWords:true, showBank:true, showSignature:true, showTerms:true, footerText:"Thank you for your business.", headerSubtitle:"Professional business document", documentTitle:"", watermarkText:"", showHsn:true, showQty:true, showRate:true, showGst:true, canvasElements:[] };
const palette=[
 {type:"text",label:"Text",icon:Type,defaultText:"Custom text"},{type:"field",label:"Field",icon:Hash,defaultText:"{{partyName}}"},{type:"logo",label:"Logo",icon:ImageIcon,defaultText:""},{type:"image",label:"Image",icon:ImageIcon,defaultText:""},{type:"line",label:"Divider",icon:Minus,defaultText:""},{type:"box",label:"Box",icon:Square,defaultText:""},{type:"items",label:"Items Table",icon:Hash,defaultText:""},{type:"total",label:"Grand Total",icon:Hash,defaultText:""},{type:"qr",label:"QR / UPI",icon:QrCode,defaultText:""}
];
const fields=["{{businessName}}","{{partyName}}","{{partyPhone}}","{{invoiceNumber}}","{{date}}","{{total}}","{{balance}}","{{gstin}}","{{address}}","{{notes}}"];
function makeElement(type, i=0){ const p=palette.find(x=>x.type===type); return {id:`el_${Date.now()}_${Math.random().toString(36).slice(2,6)}`,type,x:8+(i%3)*28,y:8+Math.floor(i/3)*13,w:type==="items"?84:type==="text"?34:22,h:type==="items"?24:type==="line"?1:type==="box"?12:7,text:p?.defaultText||"",fontSize:type==="text"?14:10,bold:type==="total",align:"left",color:"#16233f",borderColor:"#d8dde5",fill:"transparent"}; }
export default function DocumentDesigner({ business, onSave, onBack }) {
 const savedTemplates=business.documentTemplates||[]; const [style,setStyle]=useState({...blank,...(business.documentStyle||{}),canvasElements:(business.documentStyle?.canvasElements||[]).map(x=>({...x}))});
 const [filter,setFilter]=useState("All Business"); const [templateName,setTemplateName]=useState(""); const [selected,setSelected]=useState(null); const [zoom,setZoom]=useState(1);
 const categories=["All Business",...new Set(DOCUMENT_DESIGNS.map(d=>d.category))]; const designs=useMemo(()=>filter==="All Business"?DOCUMENT_DESIGNS:DOCUMENT_DESIGNS.filter(d=>d.category===filter),[filter]);
 const elements=style.canvasElements||[]; const update=(id,patch)=>setStyle(s=>({...s,canvasElements:s.canvasElements.map(e=>e.id===id?{...e,...patch}:e)}));
 const add=(type)=>{const e=makeElement(type,elements.length);setStyle(s=>({...s,canvasElements:[...s.canvasElements,e]}));setSelected(e.id)};
 const remove=()=>{if(!selected)return;setStyle(s=>({...s,canvasElements:s.canvasElements.filter(e=>e.id!==selected)}));setSelected(null)};
 const save=async(next=style,templates=savedTemplates)=>onSave(next,templates);
 const saveTemplate=async()=>{const name=templateName.trim();if(!name)return alert("Enter a template name");const tpl={id:`tpl_${Date.now()}`,name,style:{...style,preset:"custom",templateId:`tpl_${Date.now()}`}};await save(style,[...savedTemplates,tpl]);setTemplateName("");alert("Template saved.")};
 const deleteTemplate=async(id)=>{if(confirm("Delete this saved template?"))await save(style,savedTemplates.filter(t=>t.id!==id))}; const choose=d=>setStyle(s=>({...s,...d,canvasElements:s.canvasElements||[]}));
 const onDragStart=(ev,type)=>ev.dataTransfer.setData("type",type); const drop=(ev)=>{ev.preventDefault();const type=ev.dataTransfer.getData("type");if(!type)return;const r=ev.currentTarget.getBoundingClientRect();const e=makeElement(type,elements.length);e.x=Math.max(1,Math.min(92,((ev.clientX-r.left)/r.width)*100-6));e.y=Math.max(1,Math.min(92,((ev.clientY-r.top)/r.height)*100-3));setStyle(s=>({...s,canvasElements:[...s.canvasElements,e]}));setSelected(e.id)};
 const move=(ev,e)=>{if(ev.button!==0)return;ev.preventDefault();setSelected(e.id);const start={x:ev.clientX,y:ev.clientY};const r=ev.currentTarget.parentElement.getBoundingClientRect();const ox=e.x,oy=e.y;const mm=m=>update(e.id,{x:Math.max(0,Math.min(94,ox+(m.clientX-start.x)/r.width*100)),y:Math.max(0,Math.min(96,oy+(m.clientY-start.y)/r.height*100))});const up=()=>{window.removeEventListener("mousemove",mm);window.removeEventListener("mouseup",up)};window.addEventListener("mousemove",mm);window.addEventListener("mouseup",up)};
 return <div>
  <button className="bb-back" onClick={onBack}><ArrowLeft size={15}/> Back</button>
  <div className="bb-card designer-hero"><div><div className="bb-section-title"><Palette size={17}/> Document Studio — Drag & Drop Designer</div><p>Build your own Invoice, Estimate and Payment In layout. Drag blocks onto the page, move them freely and customize every block.</p></div><div className="designer-hero-badge"><Sparkles size={15}/> Your canvas, your rules</div></div>
  <div className="designer-workspace">
   <aside className="bb-card designer-sidebar"><div className="bb-section-title">Add to document</div><p className="designer-help">Drag a block to the canvas or click it.</p>{palette.map(p=>{const I=p.icon;return <button key={p.type} draggable onDragStart={e=>onDragStart(e,p.type)} onClick={()=>add(p.type)} className="designer-palette-item"><I size={15}/><span>{p.label}</span><Plus size={13}/></button>})}<div className="bb-section-title" style={{marginTop:18}}>Quick fields</div><div className="designer-field-pills">{fields.map(f=><button key={f} onClick={()=>{const e=makeElement("field",elements.length);e.text=f;setStyle(s=>({...s,canvasElements:[...s.canvasElements,e]}));setSelected(e.id)}}>{f}</button>)}</div></aside>
   <section className="bb-card designer-canvas-card"><div className="designer-canvas-toolbar"><span><Move size={14}/> A4 canvas</span><span>{elements.length} custom blocks</span><label>Zoom <input type="range" min=".65" max="1.35" step=".05" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label></div>
    <div className="designer-canvas-scroll"><div className="designer-canvas" style={{transform:`scale(${zoom})`,transformOrigin:"top center"}} onDragOver={e=>e.preventDefault()} onDrop={drop}>
      <div className="designer-canvas-base"><div className="designer-base-title">{style.documentTitle||"INVOICE"}</div><div className="designer-base-brand">{business.name||"YOUR BUSINESS"}</div><div className="designer-base-lines"/></div>
      {elements.map(e=><div key={e.id} onMouseDown={ev=>move(ev,e)} onClick={ev=>{ev.stopPropagation();setSelected(e.id)}} className={`designer-element ${selected===e.id?"active":""}`} style={{left:`${e.x}%`,top:`${e.y}%`,width:`${e.w}%`,height:`${e.h}%`,fontSize:e.fontSize,color:e.color,background:e.fill,borderColor:e.borderColor,textAlign:e.align,fontWeight:e.bold?700:400}}>{e.type==="logo"?<div className="designer-logo">LOGO</div>:e.type==="image"?<div className="designer-image">IMAGE</div>:e.type==="line"?<div className="designer-line"/>:e.type==="box"?<div className="designer-box"/>:e.type==="items"?<div className="designer-table"><i/><i/><i/><i/></div>:e.type==="total"?<b>₹ 48,500</b>:e.type==="qr"?<div className="designer-qr">▦</div>:e.text||"Text"}</div>)}
    </div></div>
    {selected&&<div className="designer-inspector"><div className="bb-section-title">Selected block</div>{(()=>{const e=elements.find(x=>x.id===selected);if(!e)return null;return <><div className="designer-inspector-grid"><label>Text<input className="bb-input" value={e.text||""} onChange={x=>update(e.id,{text:x.target.value})}/></label><label>Font size<input className="bb-input" type="number" min="7" max="60" value={e.fontSize||10} onChange={x=>update(e.id,{fontSize:Number(x.target.value)})}/></label><label>Width %<input className="bb-input" type="number" min="2" max="100" value={e.w} onChange={x=>update(e.id,{w:Number(x.target.value)})}/></label><label>Height %<input className="bb-input" type="number" min="1" max="100" value={e.h} onChange={x=>update(e.id,{h:Number(x.target.value)})}/></label><label>Text color<input type="color" value={e.color||"#16233f"} onChange={x=>update(e.id,{color:x.target.value})}/></label><label>Fill<input type="color" value={e.fill&&e.fill!=="transparent"?e.fill:"#ffffff"} onChange={x=>update(e.id,{fill:x.target.value})}/></label><label>Align<select className="bb-select" value={e.align||"left"} onChange={x=>update(e.id,{align:x.target.value})}><option>left</option><option>center</option><option>right</option></select></label><label><span>Bold</span><input type="checkbox" checked={!!e.bold} onChange={x=>update(e.id,{bold:x.target.checked})}/></label></div><button className="bb-btn bb-btn-danger" onClick={remove}><Trash2 size={14}/> Delete block</button></>})()}</div>}
   </section>
  </div>
  <div className="bb-card"><div className="bb-section-title">Ready-made templates</div><div className="designer-filter-row">{categories.map(c=><button key={c} className={`bb-chip ${filter===c?"active":""}`} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="bb-design-grid">{designs.map(d=><button key={d.id} className={`bb-design-card ${style.preset===d.id?"selected":""}`} onClick={()=>choose(d)}><div className="bb-design-preview" style={{"--preview-accent":d.accent}}><div className={`bb-design-preview-head ${d.header}`}><i/><b>YOUR BUSINESS</b><span>INVOICE</span></div><small>{d.category}</small><div className="bb-design-lines"><i/><i/><i/><i/></div><strong>₹ 48,500</strong></div><div className="bb-design-name"><span>{d.name}</span>{style.preset===d.id&&<Check size={14}/>}</div><div className="bb-design-category">{d.category}</div></button>)}</div></div>
  {savedTemplates.length>0&&<div className="bb-card"><div className="bb-section-title">My Templates</div><div className="my-template-grid">{savedTemplates.map(t=><div className="my-template-card" key={t.id}><button onClick={()=>setStyle({...t.style,canvasElements:t.style?.canvasElements||[]})}><span>{t.name}</span><small>Drag & drop custom template</small></button><button className="bb-icon-btn" title="Delete" onClick={()=>deleteTemplate(t.id)}><Trash2 size={14}/></button></div>)}</div></div>}
  <div className="bb-card"><div className="bb-section-title">Global document styling</div><div className="designer-control-grid"><Field label="Accent color"><input type="color" value={style.accent} onChange={e=>setStyle({...style,accent:e.target.value,preset:"custom"})}/><input className="bb-input" value={style.accent} onChange={e=>setStyle({...style,accent:e.target.value,preset:"custom"})}/></Field><Field label="Paper background"><input type="color" value={style.paperBg} onChange={e=>setStyle({...style,paperBg:e.target.value,preset:"custom"})}/></Field><Field label="Border color"><input type="color" value={style.lineColor} onChange={e=>setStyle({...style,lineColor:e.target.value,preset:"custom"})}/></Field><Field label="Font"><select className="bb-select" value={style.font} onChange={e=>setStyle({...style,font:e.target.value,preset:"custom"})}><option>Inter</option><option>Georgia</option></select></Field><Field label="Document title"><input className="bb-input" value={style.documentTitle} onChange={e=>setStyle({...style,documentTitle:e.target.value,preset:"custom"})}/></Field><Field label="Watermark"><input className="bb-input" value={style.watermarkText} onChange={e=>setStyle({...style,watermarkText:e.target.value,preset:"custom"})}/></Field></div><div className="designer-checks">{[["showLogo","Show logo"],["showTaxSummary","Show tax summary"],["showAmountWords","Show amount in words"],["showBank","Show bank details"],["showSignature","Show signature"],["showTerms","Show terms"],["showHsn","Show HSN/SAC"],["showQty","Show quantity"],["showRate","Show price"],["showGst","Show GST"]].map(([k,l])=><label key={k}><input type="checkbox" checked={style[k]!==false} onChange={e=>setStyle({...style,[k]:e.target.checked,preset:"custom"})}/>{l}</label>)}</div><div className="designer-save-row"><input className="bb-input" placeholder="My template name" value={templateName} onChange={e=>setTemplateName(e.target.value)}/><button className="bb-btn bb-btn-ghost" onClick={saveTemplate}><Save size={14}/> Save as My Template</button><button className="bb-btn bb-btn-primary" onClick={()=>save()}><Check size={14}/> Apply Design</button></div></div>
 </div>
}
function Field({label,children}){return <div className="bb-field"><label>{label}</label><div style={{display:"flex",gap:8,alignItems:"center"}}>{children}</div></div>}
