import { useEffect, useState } from "react";
import { Plus, Search, Trash2, ArrowDownToLine, ArrowUpFromLine, History } from "lucide-react";
import * as api from "../api";

export default function ProductsPage(){
 const [items,setItems]=useState([]),[q,setQ]=useState(""),[form,setForm]=useState({name:"",hsn:"",unit:"pcs",rate:"",gstPct:"",stock:""}),[stockFor,setStockFor]=useState(null),[movements,setMovements]=useState([]),[movement,setMovement]=useState({type:"in",qty:"",note:""});
 const load=()=>api.getProducts().then(setItems);
 useEffect(()=>{ load().catch(()=>{}); },[]);
 const save=async()=>{if(!form.name.trim())return;const x=await api.createProduct(form);setItems(v=>[...v,x]);setForm({name:"",hsn:"",unit:"pcs",rate:"",gstPct:"",stock:""});};
 const del=async id=>{await api.deleteProduct(id);setItems(v=>v.filter(x=>x.id!==id));};
 const openStock=async x=>{setStockFor(x);setMovement({type:"in",qty:"",note:""});setMovements(await api.getStockMovements(x.id).catch(()=>[]));};
 const submitStock=async()=>{if(!stockFor||!movement.qty)return;const r=await api.moveStock(stockFor.id,movement);setItems(v=>v.map(x=>x.id===stockFor.id?{...x,stock:r.product.stock}:x));setStockFor({...stockFor,stock:r.product.stock});setMovements(v=>[r.movement,...v]);setMovement({type:"in",qty:"",note:""});};
 const filtered=items.filter(x=>String(x.name||"").toLowerCase().includes(q.toLowerCase()));
 return <div>
 <div className="bb-page-head"><div><h2>Product Master</h2><span>Save items once, track stock, and reuse them instantly in invoices.</span></div></div>
 <div className="bb-card" style={{marginBottom:14}}><div className="bb-section-title">Add Product</div><div className="bb-row3">{["name","hsn","unit","rate","gstPct","stock"].map(k=><input key={k} className="bb-input" placeholder={{name:"Product / service",hsn:"HSN/SAC",unit:"Unit",rate:"Price",gstPct:"GST %",stock:"Opening stock"}[k]} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}</div><button className="bb-btn bb-btn-primary" style={{marginTop:10}} onClick={save}><Plus size={14}/> Save Product</button></div>
 <div className="bb-card"><div className="bb-section-title"><span>Saved Items ({items.length})</span><div className="bb-search-wrap" style={{maxWidth:260}}><Search size={14}/><input className="bb-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products"/></div></div><table className="bb-table"><thead><tr><th>Product</th><th>HSN</th><th>Price</th><th>GST</th><th>Stock</th><th>Stock Actions</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{x.name}</b><div style={{fontSize:11,color:"var(--muted)"}}>{x.unit}</div></td><td>{x.hsn||"—"}</td><td>₹{x.rate}</td><td>{x.gstPct}%</td><td><b>{x.stock}</b></td><td><button className="bb-btn bb-btn-ghost" onClick={()=>openStock(x)}><History size={13}/> Manage Stock</button></td><td><button className="bb-icon-btn" onClick={()=>del(x.id)} title="Delete"><Trash2 size={15}/></button></td></tr>)}</tbody></table>{!items.length&&<div className="bb-empty">No saved products yet.</div>}</div>
 {stockFor&&<div className="bb-modal-backdrop" onClick={()=>setStockFor(null)}><div className="bb-modal" onClick={e=>e.stopPropagation()}><div className="bb-section-title">Stock — {stockFor.name}</div><div style={{fontSize:13,color:"var(--muted)",marginBottom:12}}>Current stock: <b>{stockFor.stock}</b></div><div className="bb-form-grid"><label>Movement<select className="bb-select" value={movement.type} onChange={e=>setMovement({...movement,type:e.target.value})}><option value="in">Stock In</option><option value="out">Stock Out</option><option value="adjust">Adjust to</option></select></label><label>Quantity<input className="bb-input" type="number" min="0.01" value={movement.qty} onChange={e=>setMovement({...movement,qty:e.target.value})}/></label><label style={{gridColumn:"1/-1"}}>Note<input className="bb-input" value={movement.note} onChange={e=>setMovement({...movement,note:e.target.value})} placeholder="Purchase, sale, correction..."/></label></div><div className="bb-head-actions" style={{marginTop:14}}><button className="bb-btn bb-btn-primary" onClick={submitStock}>{movement.type==="in"?<ArrowDownToLine size={14}/>:<ArrowUpFromLine size={14}/>} Save Movement</button><button className="bb-btn bb-btn-ghost" onClick={()=>setStockFor(null)}>Close</button></div><div style={{marginTop:18}}><b>Recent movements</b>{movements.length?<div style={{marginTop:8,maxHeight:180,overflow:"auto"}}>{movements.map(m=><div key={m.id} style={{display:"flex",justifyContent:"space-between",padding:"7px 0",borderBottom:"1px solid var(--line)",fontSize:12}}><span>{m.type.toUpperCase()} · {m.note||"No note"}</span><b>{m.type==="out"?"-":m.type==="in"?"+":"→"}{m.qty}</b></div>)}</div>:<div className="bb-empty">No movements yet.</div>}</div></div></div>}
 </div>;
}
