import { useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import * as api from "../api";
export default function RecurringPage({docs=[]}){
 const [items,setItems]=useState([]),[form,setForm]=useState({name:"",partyName:"",frequency:"monthly",nextDate:new Date().toISOString().slice(0,10),dueDays:7,amount:""});
 useEffect(()=>{api.getRecurring().then(setItems).catch(()=>{})},[]);
 const create=async()=>{if(!form.partyName||!form.amount)return;const x=await api.createRecurring({...form,items:[{id:"recurring",name:form.name||"Recurring service",qty:1,rate:Number(form.amount),gstPct:18}],discountAmt:0});setItems(v=>[x,...v]);setForm({name:"",partyName:"",frequency:"monthly",nextDate:new Date().toISOString().slice(0,10),dueDays:7,amount:""})};
 const del=async id=>{if(!confirm("Delete this recurring schedule?"))return;await api.deleteRecurring(id);setItems(v=>v.filter(x=>x.id!==id))};
 return <div><div className="bb-page-head"><div><h2>Recurring Invoices</h2><span>Save repeat billing schedules and keep the next invoice date ready.</span></div></div><div className="bb-card" style={{marginBottom:14}}><div className="bb-section-title"><Plus size={15}/> New Recurring Schedule</div><div className="bb-row3"><input className="bb-input" placeholder="Schedule name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="bb-input" placeholder="Customer name" value={form.partyName} onChange={e=>setForm({...form,partyName:e.target.value})}/><input className="bb-input" placeholder="Amount" type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><select className="bb-select" value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select><input className="bb-input" type="date" value={form.nextDate} onChange={e=>setForm({...form,nextDate:e.target.value})}/><input className="bb-input" type="number" value={form.dueDays} onChange={e=>setForm({...form,dueDays:e.target.value})} placeholder="Due days"/></div><button className="bb-btn bb-btn-primary" style={{marginTop:10}} onClick={create}>Save Schedule</button></div><div className="bb-card"><div className="bb-section-title">Schedules ({items.length})</div>{items.length?<table className="bb-table"><thead><tr><th>Schedule</th><th>Customer</th><th>Frequency</th><th>Next invoice</th><th>Amount</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{x.partyName}</td><td>{x.frequency}</td><td>{x.nextDate}</td><td>₹{Number(x.amount||x.items?.[0]?.rate||0).toLocaleString("en-IN")}</td><td><button className="bb-icon-btn" onClick={()=>del(x.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table>:<div className="bb-empty">No recurring schedules yet.</div>}</div></div>
}